// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
import type { Env as ApiEnv } from './src/API/http';

interface Env extends ApiEnv {
	ASSETS: Fetcher;
}
